services:
  app:
    image: kixyu9527/tg_bot:latest
    container_name: tg-bot-app
    restart: always
    networks:
      - 1panel-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tg_bot_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_PROFILES_ACTIVE: dev
      TELEGRAM_BOT_TOKEN: ""
      TELEGRAM_BOT_OWNER_ID: ""
      TELEGRAM_BOT_GROUP_ID: ""
      TELEGRAM_BOT_WEBHOOK_URL: ""
      TELEGRAM_BOT_WEBHOOK_SECRET: ""
    ports:
      - "9599:9599"

networks:
  1panel-network:
    external: true
